name: Deploy React App

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # Set environment based on the branch that triggered the workflow
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || github.ref == 'refs/heads/staging' && 'staging' || 'development' }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Set environment based on branch
      id: set-env
      run: |
        if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
          echo "environment=development" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
          echo "environment=staging" >> $GITHUB_OUTPUT
        elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "environment=production" >> $GITHUB_OUTPUT
        fi
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:${{ steps.set-env.outputs.environment }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/react-app:${{ github.sha }}

    - name: Deploy to environment
      uses: appleboy/ssh-action@master
      env:
        ENVIRONMENT: ${{ steps.set-env.outputs.environment }}
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        envs: ENVIRONMENT
        script: |
          docker-compose pull
          docker-compose up -d \
            -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            -e REACT_APP_ENV=$ENVIRONMENT 