name: Deploy React App

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/react-app:${{ github.event.release.tag_name }}
          your-dockerhub-username/react-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        environment: [development, staging, production]
    
    environment: ${{ matrix.environment }}
    
    steps:
    - name: Deploy to environment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker-compose pull
          docker-compose up -d \
            -e REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            -e REACT_APP_ENV=${{ matrix.environment }} \
            # Add other environment variables as needed 